api_platform:
    # The title of the API.
    title: 'CRM API'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '0.1.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
#    resource_class_directories:
#        - '%kernel.project_dir%/src/Dto'