framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
        paths:
            - '%kernel.project_dir%/src/EntityMakerBundle/Resources/translations'
